version: '3.8'

services:
  channels_backend:
    image: channels-backend
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./.env.backend:/usr/src/app/channels-backend/.env
  channels_frontend:
    image: channels-frontend
    depends_on:
      - channels_backend
    build: .
    ports:
      - 5173:5173
    volumes:
      - ./.env.frontend:/usr/src/app/channels-frontend/.env
